IIP-Design/cdp-content-commons

src/components/Results/ResultItem/ResultItem.scss
=> CDP-587 - Hide result Item excerpt from list view on mobile

package-lock.json, package.json, public/index.html, src/App.js, src/components/Results/ResultItem/ResultItem.scss, src/index.js
- IE 11 flexbox fix for image display on search result items
=> CDP 598 - IE11 Flexbox Fix

src/components/Footer/Footer.js, src/components/Footer/Footer.scss
- Added Contact Us link to footer, added padding to link style.
- Copy edits to footer text.
=> Add Contact Us to footer. Edits to footer text.

package-lock.json, src/components/Recents/Recents.scss
- adjust Recents styling to avoid overlap on mobile, phablet displays
=> Landing Page (Recents Component) Text Overlap on Mobile

package-lock.json, src/components/Modals/ModalItem/ModalItem.scss
- position close icon within modal
=> Modal Close Icon

src/components/Modals/ModalItem/ModalItem.scss
- add ipad css targeting for modal close icon
=> Modal Close Icon - Ipad CSS

src/components/Header/Header.scss, src/components/Nav/Nav.scss
- increase font size for nav, header subtext
- add letter spacing to nav text
=> CDP-636 - Font Size/Letter Spacing

src/components/Popup/Popup.scss, src/components/Types/Video/Video.scss
- add scrolling to popup tab items
- ie: 10 SRT links, only a few show bc abs positioned, the rest off screen
- added max-height, overflow-y: auto to segment tab
=> CDP-630 - Download Popup

src/components/Modals/ModalItem/ModalItem.scss
- css edit for Modal X icon to display properly across browsers, devices
- IE 11, Edge, Safari, Chrome, FF, Ipad
=> CDP - 656 - Modal X Icon Display

src/components/Popup/Popup.scss, src/components/Popup/PopupTrigger.js
- center carrot and edit color
- move blue gradient line to top
- move popup close to right edge
- tested IE11, Edge, Chrome, FF, Safari
=> CDP-687 - css edits for Download/Share Popup

src/components/Pages/BasePage.scss, src/components/Pages/PageTmpl.js
- fix for style conflict on Modal windows
=> Modal Styling Issue 7/12

client/src/components/Footer/index.js, client/src/components/Modals/ModalImage/ModalImage.js, client/src/components/Modals/ModalImage/ModalImage.scss, client/src/components/Modals/ModalItem/ModalItem.scss, client/src/components/Types/Post/Post.js, client/src/utils/helpers.js, client/src/utils/parser.js
Namely:
1. Adds captions and alt text to search result modals
1. Constrains the figure width to 100% in modals to prevent overflow when figure has a defined width
1. Replaces language_code with locale as the key for modal language switcher dropdown (to stay consistent throughout app)
=> CDP-864: Porting over changes from develop to v2

src/components/ClipboardCopy/ClipboardCopy.js, src/components/ClipboardCopy/ClipboardCopy.scss, src/components/Types/Video/Video.scss
- revert embed code, share link to original design
- addressed vertical scrollbar on download video hover state on IE11
=> CDP-839 - Popup Embed/Share copy button display, download video hover edit

src/components/Types/Post/Post.js
-Remove spacing btwn div & script tag on embed code for Articles
=> Article Embed Code Spacing

src/components/Popup/Popup.scss, src/components/Popup/PopupTrigger.js, src/components/Types/Video/Video.js
- increased width of mobile Popup
- edit popup pointer to position dynamically
=> CDP-838 - Mobile Popup Display

src/components/Search/Search.js, src/components/Search/Search.scss
=> CDP-948 - add onclick handler to search icon

src/components/Heading/Heading.js
removed "Connecting people with content."
=> CDP-1024 - update subheading text

src/utils/helpers.js
Escaped quotes before query gets sent to ES so that ES properly interprets them even with an odd number.
=> CDP-1031: Typing in odd number of double quotations in the search field result in an error.

src/components/Footer/Footer.js
Updated the Slack channel in the footer to content-commons.
=> Update slack channel to content-commons

src/components/Types/Video/DownloadSrt.js, src/components/Types/Video/DownloadVideo.js, src/components/Types/Video/Video.js, src/utils/withFileDownload.js
Added a defaultTitle prop to DownloadSrt and DownloadVideo which will always be the first available English title or 'Commons Video' if not.
=> CDP-737: Retain Naming Convention on SRT Download

src/components/Types/Video/DownloadTranscript.js, src/components/Types/Video/Video.js
Switched the download href to use downloadLink function for generating the link URL.
=> CDP-1129: Update filename convention for Transcripts like Video and SRT

src/components/Footer/Footer.js
- Updates IIP to GPA
- Updates link for GPA
- Updates Copyright to GPA and 2019
=> Updates Footer for GPA
